Refs #1003: Used system font stack for sans-serif text.
django/djangoproject.com pull request #1232
Opened 2022-10-09 11:19 UTC by knyghty

Looks a bit worse to my eye but maybe it's okay.

Before:
<img width="1509" alt="Screenshot 2022-10-09 at 11 51 29" src="https://user-images.githubusercontent.com/3871354/194753935-b7bff007-803d-49a6-94b1-c1f4542a3cc1.png">

After:
<img width="1512" alt="Screenshot 2022-10-09 at 11 51 40" src="https://user-images.githubusercontent.com/3871354/194753943-6225c03a-ccf8-4b06-8d19-d24cd484e2a7.png">

2022-10-09 13:02 UTC, pauloxnet requested changes

2022-10-09 13:02 UTC, pauloxnet commented on djangoproject/templates/styleguide.html
> +      The serif font is <em>Palatino</em>, which is widely available as a system font.
Actually "Palatino" is not present in my Ubuntu 22.04, the only font of the "serif" list present on Ubuntu is "Georgia". But we can review this point in another PR.

2022-10-09 13:11 UTC, knyghty commented on djangoproject/scss/_utils.scss
> +        "Noto Color Emoji";
The problem with this is that putting `system-ui` first creates huge problems for certain languages, see in particular [this comment](https://code.djangoproject.com/ticket/33878#comment:3) on the ticket, and [this post](https://infinnie.github.io/blog/2017/systemui.html).

2022-10-09 13:12 UTC, knyghty commented on djangoproject/scss/_utils.scss
> +        "Noto Color Emoji";
On Linux you're unlikely to have Segoe UI unless you installed it yourself, both -apple-system and BlinkMacSystemFont do nothing, so on Linux you should get the expected font.

2022-10-09 13:43 UTC, pauloxnet commented on djangoproject/scss/_utils.scss
> +        "Noto Color Emoji";
Sure you know the subject better than me, I have looked at your article, but it seems strange to me that it is somehow at odds with this other one [here](https://booking.design/implementing-system-fonts-on-booking-com-a-lesson-learned-bdc984df627f).

As for the support for fonts on Linux I must say that so far it has been a bit lacking despite being by far the most used operating system among [Django developers](https://lp.jetbrains.com/django-developer-survey-2021-486/#circular-chart-685) and therefore visit his site.

Obviously mine is not a complaint but a proposal for improvement, so I proposed the insertion of Linux specific fonts in the list.

2022-10-13 08:44 UTC, knyghty commented on djangoproject/scss/_utils.scss
> +        "Noto Color Emoji";
So I'm not really against it, but I don't think it achieves much, because as long as you're using a modern browser `system-ui` will (should?) just take whatever font your window manager / desktop environment is using. I also think that it's nice to keep in sync with what we have in the Django admin (which was taken from Wagtail, and I believe they put quite a bit of effort into researching that stack).

2022-10-13 09:09 UTC, pauloxnet commented on djangoproject/scss/_utils.scss
> +        "Noto Color Emoji";
Ok, I agree and have the two list on sync with the Django admin.
I'll resolve this conversation and then I'll propose to add this Linux fonts on the django core.

2022-10-13 09:09 UTC, pauloxnet approved these changes

2022-10-13 11:11 UTC, merged

2022-10-13 17:16 UTC, MarkusH commented
> Hey there, this shouldn't be done like this, there was non-trivial amount of effort and money spent on typography for the website, please reconsider this.

Frankly, using Google fonts is pretty much impossible these days, as far as I can tell (IANAL, https://rewis.io/urteile/urteil/lhm-20-01-2022-3-o-1749320/).

2022-10-13 17:44 UTC, camilonova commented
So, it would be better to use Roboto instead of a system font.

I agree it makes sense if the font can be hosted directly.