Add Open Graph tags (#1144)
django/djangoproject.com pull request #1249
Opened 2022-10-16 11:56 UTC by marksweb

This adds Open Graph tags to address #1144.

The approach is to keep it fairly simple, with blocks where possible in the base template to allow overrides where necessary in other templates.

2022-10-16 12:00 UTC, marksweb commented
:wave: @pauloxnet @carltongibson 

Thought I'd get OG tags integrated & before going too far, I thought it'd be worth showing you guys the general approach I was taking incase you had your own thoughts on the matter.

So far I've gone with the basic few tags for `og` and `twitter`, using `block` tags to allow specific pages to overwrite content, like the download page using the image of the roadmap which I think would be useful.

2022-10-16 15:46 UTC, nemecek-filip commented
Hi!

Twitter also has support for OG tags so that is possibly something to consider - could be worth it - considering you then need to maintain fewer tags - https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup

Also the image one seem to need full URL otherwise they often fail to display.

2022-10-16 17:03 UTC, marksweb commented
@nemecek-filip thanks I didn't realise that about the twitter tags.

And as I understand it, the project uses an absolute url for the static tag in production. At least that's what it looks like comparing the production source to the production static url setting. It's on a sub domain of static.djangoproject.com

2022-10-16 17:37 UTC, nemecek-filip commented
@marksweb oh I see. Apologies for the false alarm! Did not consider that the paths could be absolute by default.

2022-10-16 17:47 UTC, marksweb commented
@nemecek-filip not to worry, it's rare to see static setup this way. The vast majority of projects stick to `/static` like the default sets us up for

2022-11-07 16:37 UTC, marksweb commented
@pauloxnet No need to apologise. 

Understood 👍

2022-11-07 20:22 UTC, pauloxnet commented on djangoproject/templates/overview.html
> +{% block og_title %}Django overview{% endblock %}
Moving existing code as little as possible helps reviewers
```suggestion
{% block title %}Django overview{% endblock %}
{% block layout_class %}full-width{% endblock %}
{% block og_title %}Django overview{% endblock %}
```

2022-11-07 20:22 UTC, pauloxnet commented on .gitignore
> +# If you need to exclude files such as those generated by an IDE, use
This change seems out of scope for this PR.

2022-11-07 20:22 UTC, pauloxnet commented on djangoproject/templates/releases/download.html
> +{% block og_description %}The latest official version is {{ current.version }}{% if current.is_lts %} (LTS){% endif %}{% endblock %}
See above
```suggestion
{% block title %}Download Django{% endblock %}
{% block layout_class %}sidebar-right{% endblock %}
{% block og_title %}Download Django{% endblock %}
{% block og_image %}{% static "img/release-roadmap.png" %}{% endblock %}
{% block og_image_alt %}Django's release roadmap{% endblock %}
{% block og_description %}The latest official version is {{ current.version }}{% if current.is_lts %} (LTS){% endif %}{% endblock %}
```

2022-11-08 01:30 UTC, marksweb commented on .gitignore
> +# If you need to exclude files such as those generated by an IDE, use
While you're absolutely right, this is one of those things that would help new contributors & otherwise likely wouldn't get added.

2022-11-13 18:26 UTC, pauloxnet approved these changes

2022-11-14 07:49 UTC, pauloxnet commented
@marksweb your PR is ok for me. One last question: have you check locally with some Open Graph reader or checker (e.g. [share preview](https://github.com/rafaelmardojai/share-preview/)) ?

2022-11-14 08:19 UTC, pauloxnet commented
I'm going to verify locally all the pages to check if all OG tags are ok.

2022-11-14 09:23 UTC, marksweb commented
@pauloxnet I did some testing of the markup in another project to verify. However I'm not aware of a tool for testing tags locally on macOS.

2022-11-14 16:00 UTC, pauloxnet requested changes
I've tried all the pages locally with a Open Graph viewer and I've added some change suggestions.

2022-11-14 16:06 UTC, marksweb commented
Thanks @pauloxnet - all changes committed.

2022-11-14 16:11 UTC, pauloxnet approved these changes

2022-11-14 16:12 UTC, merged

2022-11-14 16:13 UTC, pauloxnet commented
> Thanks @pauloxnet - all changes committed.

That was fast. Thanks @marksweb for your workj and patience. I've just merged.