Fix feed aggregator n+1 issue [#1261]
django/djangoproject.com pull request #1274
Opened 2022-11-19 13:22 UTC by marksweb

This addresses the regression in #1261 and adds caching for feed items.

Items are cached for 24 hours and invalidated on saving or deleting `FeedType` and `FeedItem`.

Prior to this the community page had 10 queries. The initial `select_related` brought it down to 7 and then the caching brings it down to 4.

2022-11-19 15:29 UTC, carltongibson reviewed
Hey @marksweb. Sounds nice. Can I ask you to add some tests so we can avoid regressions in the future?

2022-11-19 17:12 UTC, marksweb commented
@carltongibson yeah very good point 👍

2022-11-19 20:17 UTC, marksweb commented
@carltongibson Ok I've added a test so now those 4 queries I mentioned are set in stone/tests

2022-11-30 12:00 UTC, carltongibson requested changes
Hey @marksweb — Thanks for this, I've left some comments.

> Q: is the select_related in ft.items() not enough to solve the N+1 issue?

Can we perhaps try a small commit adding that (with an appropriate assertNumQueries) and then look at caching separately? I think it might be better to cache the page — or the full template fragment, rather than each of the FeedItems fetches separately. 🤔

2022-11-30 12:00 UTC, carltongibson commented on djangoproject/templates/aggregator/index.html
> +{% for feedtype, latest_items in feed_data %}
Equally, we could cache this template fragment. 🤔

2022-11-30 12:45 UTC, marksweb commented on aggregator/models.py
> +        return items
@carltongibson Sure I can move to the manager. This was a matter of habit that I did it this way.

2022-11-30 12:47 UTC, marksweb commented
> Can we perhaps try a small commit adding that (with an appropriate assertNumQueries) and then look at caching separately? I think it might be better to cache the page — or the full template fragment, rather than each of the FeedItems fetches separately. 🤔

@carltongibson I can certainly keep this simple for now and remove all the caching side of the changes. As I said, that drops the queries to 7 & I just saw an easy opportunity to save a few more.

I'll remove the caching and that can be addressed separately.

2022-11-30 12:49 UTC, carltongibson commented
Cool. Thanks. 

I'm not against the caching... — I'm just not quite sure about the approach here (vs page or template cache, for example.) Better if we handle that separately. 

🎁

2022-11-30 12:52 UTC, marksweb commented
@carltongibson Yeah that's no problem. I just don't do template caching outside of a cached loader so happy to adjust to suit the project. I get used to caching at that query level because data might get pulled out in various places.

Shall I raise a new PR on a clean branch to make the `select_related` change and leave this here for discussion on caching?

2023-09-20 23:07 UTC, closed without merging