Fixed Overflow Issue
django/djangoproject.com pull request #1353
Opened 2023-04-28 17:27 UTC by Tushar-sahani

Fixed overflow issue of text in the Documentation.

2023-05-10 17:31 UTC, Tushar-sahani commented
I have attached the screenshots and video in the issue itself, after adding the overflow-wrap property . Should I add the screenshots with the PR ?

2023-05-10 22:10 UTC, sabderemane commented
> I have attached the screenshots and video in the issue itself, after adding the overflow-wrap property . Should I add the screenshots with the PR ?

Yes please, better to have them in the PR related, I will close the issue in order to keep the older one as the current issue linked.

2023-05-11 04:46 UTC, Tushar-sahani commented
In most of the Documentation Have this problem where ```span.pre``` and ```tt``` these two tags are used.

## Before
![1](https://github.com/django/djangoproject.com/assets/104075614/916cfcbd-f0eb-4ff5-ba31-8228b12b415c)
![2](https://github.com/django/djangoproject.com/assets/104075614/49aea018-aa54-4490-975d-e65188f8ca24)

https://github.com/django/djangoproject.com/assets/104075614/63560f93-f373-4cc9-b3c0-55472dad1f7f

## After

![fixed1](https://github.com/django/djangoproject.com/assets/104075614/883e117f-7b59-489c-96fe-0d531d6479fd)
![Screenshot (9)](https://github.com/django/djangoproject.com/assets/104075614/02f1df52-2881-4f13-b668-9a5aa38ffb66)

2023-05-11 11:53 UTC, sabderemane approved these changes

2023-05-19 12:38 UTC, sabderemane requested changes

2023-05-19 12:38 UTC, sabderemane commented on djangoproject/scss/_style.scss
> +    overflow-wrap: break-word;
After some discussion, I think it would be better to have the `overflow-wrap` only on the bloc needed to avoid problems in places we didn't expect.

2023-06-02 11:46 UTC, sabderemane approved these changes
I've done a small fix to your PR, thank you for your contribution @Tushar-sahani 🎉 

Welcome on board ⛵

2023-06-02 11:50 UTC, merged