Changes header navigation to a <nav> element, style by ID
django/djangoproject.com pull request #1369
Opened 2023-06-01 15:37 UTC by devanubis

2023-06-02 10:13 UTC, cgl commented
🐼 Thank you for the PR, could you please enter a description of what it is solving, etc.

2023-06-02 12:27 UTC, knyghty approved these changes

2023-07-13 01:57 UTC, sabderemane requested changes

2023-07-13 01:57 UTC, sabderemane commented on djangoproject/scss/_style.scss
> +		background: $green-dark;
A closing curly brace is missing, could you please look to fix it ?

2023-07-13 01:57 UTC, sabderemane commented on djangoproject/scss/_style.scss
> +	#header-navigation {
Did you wanted to replace `[role="navigation"]` by `#header-navigation` ?

2023-09-14 20:41 UTC, devanubis commented on djangoproject/scss/_style.scss
> +	#header-navigation {
Sorry, completely missed the notifications for these and don't often use the github list of open PRs.

Fixed, can't believe I missed that.

2023-09-27 00:09 UTC, sabderemane reviewed
Thank you for the updates @devanubis, I'm afraid there are others changes needed: `role="navigation"` is used in 3 others pages : `search_result.html`, `feeditem_list.html,` `blog_pagination.html` so changing the style in _style.scss will impact those 3 elements.

Plus, did you check if it's rendering correctly on mobile ?

2025-05-16 23:19 UTC, adamzap commented
@devanubis Could you address the comments on this PR if you're still interested in working on it? Otherwise I'll close it in a week. Thanks!

2025-05-30 16:53 UTC, adamzap commented
I'm closing this due to inactivity.

2025-05-30 16:53 UTC, closed without merging