Fix #1276: Add copy to clipboard for commands
django/djangoproject.com pull request #1434
Opened 2023-11-26 07:34 UTC by prashantpandey9

- Fixes #1276 

Screenshot for reference

![image](https://github.com/django/djangoproject.com/assets/44068293/b67e00bd-936e-4b94-b8bd-446533b746dc)

![image](https://github.com/django/djangoproject.com/assets/44068293/f4ef216f-eedb-4f12-a0d5-d7e446dac825)

![image](https://github.com/django/djangoproject.com/assets/44068293/4536de9d-cd68-42f7-b5e5-d3a6301f291b)

![image](https://github.com/django/djangoproject.com/assets/44068293/b2663fcb-4fc7-4fbc-b649-6de97a32da46)

![image](https://github.com/django/djangoproject.com/assets/44068293/f544871c-6096-4501-be1e-606446c86096)

2023-12-05 16:30 UTC, nvishnya commented
Commands for both Linux and Windows are copied no matter what tab is opened. Promts are also copied ($, ...\>).
![test](https://github.com/django/djangoproject.com/assets/23117124/f93031f6-cba9-4ede-87bc-d58dd8679c11)

2023-12-06 12:47 UTC, prashantpandey9 commented
hi @nvishnya  Thanks for highlighting it. WIll check and try to improve this.

> Commands for both Linux and Windows are copied no matter what tab is opened. Promts are also copied ($, ...>). ![test](https://private-user-images.githubusercontent.com/23117124/288125000-f93031f6-cba9-4ede-87bc-d58dd8679c11.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NjY5MTIsIm5iZiI6MTcwMTg2NjYxMiwicGF0aCI6Ii8yMzExNzEyNC8yODgxMjUwMDAtZjkzMDMxZjYtY2JhOS00ZWRlLTg3YmMtZDU4ZGQ4Njc5YzExLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDEyNDMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxMzc2YTJiYWI3NjRlNDc1ODgwOWNmMjBlMWM5NDU2OTY4ZWFiODZmYWRiMTg1ZWM4YWIwYjEzZTE5ZDIxM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ys0okuwZ0DDYRZ8LeWSH0ewwI87kzzIlS7Mvi5pzBUo) [ ![test](https://private-user-images.githubusercontent.com/23117124/288125000-f93031f6-cba9-4ede-87bc-d58dd8679c11.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NjY5MTIsIm5iZiI6MTcwMTg2NjYxMiwicGF0aCI6Ii8yMzExNzEyNC8yODgxMjUwMDAtZjkzMDMxZjYtY2JhOS00ZWRlLTg3YmMtZDU4ZGQ4Njc5YzExLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDEyNDMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxMzc2YTJiYWI3NjRlNDc1ODgwOWNmMjBlMWM5NDU2OTY4ZWFiODZmYWRiMTg1ZWM4YWIwYjEzZTE5ZDIxM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ys0okuwZ0DDYRZ8LeWSH0ewwI87kzzIlS7Mvi5pzBUo) ](https://private-user-images.githubusercontent.com/23117124/288125000-f93031f6-cba9-4ede-87bc-d58dd8679c11.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NjY5MTIsIm5iZiI6MTcwMTg2NjYxMiwicGF0aCI6Ii8yMzExNzEyNC8yODgxMjUwMDAtZjkzMDMxZjYtY2JhOS00ZWRlLTg3YmMtZDU4ZGQ4Njc5YzExLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDEyNDMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxMzc2YTJiYWI3NjRlNDc1ODgwOWNmMjBlMWM5NDU2OTY4ZWFiODZmYWRiMTg1ZWM4YWIwYjEzZTE5ZDIxM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ys0okuwZ0DDYRZ8LeWSH0ewwI87kzzIlS7Mvi5pzBUo) [ ](https://private-user-images.githubusercontent.com/23117124/288125000-f93031f6-cba9-4ede-87bc-d58dd8679c11.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NjY5MTIsIm5iZiI6MTcwMTg2NjYxMiwicGF0aCI6Ii8yMzExNzEyNC8yODgxMjUwMDAtZjkzMDMxZjYtY2JhOS00ZWRlLTg3YmMtZDU4ZGQ4Njc5YzExLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDEyNDMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxMzc2YTJiYWI3NjRlNDc1ODgwOWNmMjBlMWM5NDU2OTY4ZWFiODZmYWRiMTg1ZWM4YWIwYjEzZTE5ZDIxM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ys0okuwZ0DDYRZ8LeWSH0ewwI87kzzIlS7Mvi5pzBUo)

2023-12-06 14:51 UTC, prashantpandey9 commented
Hi, updated the code copying logic refer below:

![ezgif com-video-to-gif (2)](https://github.com/django/djangoproject.com/assets/44068293/0970a1ae-d47a-4b7f-82f1-44b1deced110)

2024-06-09 12:07 UTC, sabderemane requested changes

2024-06-09 12:07 UTC, sabderemane commented on djangoproject/scss/_console-tabs.scss
> +                float: right;
Why do you have to use `float` here? You are using flexbox, I think it's better to keep everything in flex then

2025-05-25 17:36 UTC, sabderemane commented
Closed because no activity is reported in the PR and the code has conflicts with the Javascript files.

2025-05-25 17:36 UTC, closed without merging