Fixes focus indicators
django/djangoproject.com pull request #1545
Opened 2024-06-11 15:08 UTC by SaptakS

Refs #1381 

Improves the focus indicators. Based on WCAG 2.2 standards, it is a better idea to have solid outlines instead of a dotted outline for focus indicators. Also, color change for focus indication isn't great because it doesn't often work for color blinded people.

So things done in this PR:
- Make all anchor tags have a solid 2px outline of the currentColor (Sadly the currentColor itself doesn't meet WCAG color contrast requirement, so the focus indicator doesn't either, but hopefully that's a separate discussion)
- Apply the same above design to all buttons as well
- Adds an offsetted focus outline for the CTAs
- Moves padding in navigation elements from the `<a>` element to the `<li>` element.

These address the below concerns by @thibaudcolas in #1381 
> Focus style almost invisible on "Get started with Django" CTA

> Custom "dotted outline" focus styles: not visible enough and broken in main navigation

Attaching some screenshots of the changes:
![image](https://github.com/django/djangoproject.com/assets/9530293/91880579-8217-474b-9644-3b3bb9eda009)
![image](https://github.com/django/djangoproject.com/assets/9530293/21b7cec3-dbc6-44f8-93b5-a8943ddb0f33)

2024-06-13 13:29 UTC, bmispelon requested changes
This seems like a good change.  I've tested it locally and it works.

I have just two minor comments which don't affect the feature itself.

Thanks for working on this! ✨

2024-06-13 13:29 UTC, bmispelon commented on djangoproject/scss/_style.scss
>              }
The whole `@include` is now empty, so it can be deleted, right?

2024-06-13 13:29 UTC, bmispelon commented on djangoproject/scss/_style.scss
> +    &:hover{
Missing a space before the bracket:

```suggestion
    &:hover {
```

2024-06-13 13:57 UTC, SaptakS commented
Thanks @bmispelon for pointing those out. Have updated them.

2024-06-13 15:42 UTC, bmispelon approved these changes

2024-06-13 15:49 UTC, bmispelon commented
Thanks for the quick update. This looks good to me now, unless anyone objects I'll merge and deploy this over the coming weekend.

2024-06-14 21:01 UTC, merged

2024-06-14 21:20 UTC, bmispelon commented
And it's live, well done everybody 👏🏻