feat: Translation preparation for aggregator app
django/djangoproject.com pull request #1662
Opened 2024-10-13 19:10 UTC by marksweb

This begins the implementation of translation tags as suggested by [#1648](https://github.com/django/djangoproject.com/issues/1648)

Translations tags & gettext are added to the aggregator app with this change.

2024-10-14 13:03 UTC, bmispelon requested changes
Again, impressive work ✨ 

I found a few things that need fixing, some that can be improved, and an open question about date/time localization.

Feel free to either push new commits or amend the existing history, whatever works for you 👍🏻

2024-10-14 13:03 UTC, bmispelon commented on djangoproject/templates/aggregator/feeditem_list.html
> +        <span class='meta'>{% blocktranslate trimmed with date_modified=item.date_modified|date:"F j, Y" time_modified=item.date_modified|date:"g:i A" public_url=item.feed.public_url title=item.feed.
The particular formats (`F j, Y` and `g:i A`) used here are very english/US-centric and should vary based on locale. Is there an easy way to do that?

Just spitballing here, but what about a new `localized_date_modified` property on the `FeedItem` model? That would also help make this line a bit shorter.

2024-10-14 19:51 UTC, marksweb commented on aggregator/views.py
> +from django.utils.translation import gettext_lazy as _
Ah yes - bad habbit brought on by too much copy/paste

2024-10-14 22:52 UTC, marksweb commented on djangoproject/templates/aggregator/feeditem_list.html
> +        <span class='meta'>{% blocktranslate trimmed with date_modified=item.date_modified|date:"F j, Y" time_modified=item.date_modified|date:"g:i A" public_url=item.feed.public_url title=item.feed.
You can use the localised date formats that come from a `formats.py` file to allow customisation of these, if I recall.

`|date:"DATE_FORMAT"` will output Oct. 14, 2024 (think I'll use this)

`|date:"SHORT_DATE_FORMAT"` will output 10/14/2024 

Some of the named formats you can use can be found here; https://github.com/django/django/blob/main/django/utils/formats.py#L31

2024-10-15 19:47 UTC, marksweb commented
@bmispelon I've addressed your points, adding the localised `DATE_FORMAT` so that will get picked up by the translation system. And I added an extra translation from the feed iteration which gives the date and "by" feed to allow that to be translated also.

2024-10-16 14:05 UTC, bmispelon requested changes
Hi,

I think we should use readymade date/time formats everywhere when doing localization. I also spotted a potential issue with context-unaware translatable strings that I must have missed in my first round of review, sorry.

It's starting to look good though 👍🏻

2024-10-16 14:05 UTC, bmispelon commented on djangoproject/templates/aggregator/index.html
> +              {% translate "or" %}
This kind of piecemeal translation might not very well for some languages I can't come up with a concrete example, but I could imagine a language where the word "or" might need to be translated differently based on context.

A solution might be a refactor into a less clever if/elif/else structure where full sentences are translated.
If that's too complicated, then at the minimum we should probably use a [contextual marker](https://docs.djangoproject.com/en/5.1/topics/i18n/translation/#contextual-markers):
```suggestion
              {% translate "or" context "view more OR add your feed" %}
```

2024-10-17 08:25 UTC, marksweb commented on djangoproject/templates/aggregator/index.html
> +                {% blocktranslate trimmed with modified_date=item.date_modified|date:"N jS, Y \a\t P" public_url=item.feed.public_url title=item.feed.title %}
I could add a custom format here using the `formats.py` I've added to #1669

2024-10-17 14:28 UTC, bmispelon commented
This needs fixing after #1676 got merged

2024-10-18 14:23 UTC, marksweb commented
@bmispelon Ok I rebased main & believe this is now in a good state.

2024-10-18 20:17 UTC, bmispelon approved these changes
👏🏻

2024-10-25 16:15 UTC, merged