feat: Translation preparation for blog app
django/djangoproject.com pull request #1669
Opened 2024-10-15 19:49 UTC by marksweb

This adds translations tags to the blog app as suggested in [#1648](https://github.com/django/djangoproject.com/issues/1648)

2024-10-16 14:29 UTC, bmispelon requested changes

2024-10-16 14:29 UTC, bmispelon commented on djangoproject/templates/blog/blog_pagination.html
> +          <span class="visuallyhidden">{% translate "Previous" %}</span>
I would add a contextual marker here:
```suggestion
          <span class="visuallyhidden">{% translate "Previous" context "pagination" %}</span>
```

2024-10-16 14:29 UTC, bmispelon commented on djangoproject/templates/blog/blog_pagination.html
> +          <span class="visuallyhidden">{% translate "Next" %}</span>
```suggestion
          <span class="visuallyhidden">{% translate "Next" context "pagination" %}</span>
```

2024-10-16 14:29 UTC, bmispelon commented on djangoproject/templates/blog/entry_archive_day.html
> +{% block title %}{{ day|date:"F j" }} | {% translate "Weblog" %}{% endblock %}
As I mentionned in another PR, I think we should move to using named formats rather than hardcoded ones for localized strings:
```suggestion
{% block title %}{{ day|date:"MONTH_DAY_FORMAT" }} | {% translate "Weblog" %}{% endblock %}
```
(there's several instances of this in this file that need to be fixed too)

2024-10-16 14:29 UTC, bmispelon commented on djangoproject/templates/blog/entry_archive_month.html
> +{% block title %}{{ month|date:"F" }} | {% translate "Weblog" %}{% endblock %}
I'd use `YEAR_MONTH_FORMAT` consistently in this file:
```suggestion
{% block title %}{{ month|date:"YEAR_MONTH_FORMAT" }} | {% translate "Weblog" %}{% endblock %}
```

2024-10-16 14:29 UTC, bmispelon commented on djangoproject/templates/blog/entry_detail.html
> +    Posted by {{ author }} on {{ pub_date|date:"F j, Y" }}
The filtering needs to move to the `blocktranslate` declaration (and we should use a named format)

2024-10-16 14:29 UTC, bmispelon commented on djangoproject/templates/blog/entry_detail.html
> +        {{ object.body_html|safe }}
I think this line got indented by mistake.

Also - and this is definitely out of scope for this PR but I was wondering if you'd thought of that already - data that comes from the database such as `body_html` here should be marked with the correct `lang` HTML attribute (and we should probably store which language an entry was written in on the model).

2024-10-16 20:01 UTC, marksweb commented on djangoproject/templates/blog/blog_pagination.html
> +          <span class="visuallyhidden">{% translate "Previous" %}</span>
@bmispelon Yeah, good idea - I don't use context enough with translation!!

2024-10-16 20:54 UTC, marksweb commented on djangoproject/templates/blog/entry_detail.html
> +    Posted by {{ author }} on {{ pub_date|date:"F j, Y" }}
Ah missed this one 🤦🏼

2024-10-16 21:01 UTC, marksweb commented on djangoproject/templates/blog/entry_detail.html
> +        {{ object.body_html|safe }}
Well translating database objects is a decision that needs making as to a third party package to utilise I think.

An issue with this though is you - at least in my experience - don't get content exported to your `.po` files from the usual packages so you need to do the translations in admin. But maybe if we're storing html/markdown then files can be shared with translators and then entered into the system by someone with access.

_(I work with someone who wrote a management command that extracts database data and writes it to html files so that it can be picked up by regular translation methods)_

2024-10-16 23:16 UTC, marksweb commented
@bmispelon Bit of scope creep at the 11th hour here, but I've added a formats file to allow us to customise the datetime formats.

With this, it'd be good to get this merged before others so that I can then start using named date formats on the other apps.

2024-10-17 15:14 UTC, marksweb commented
> I don't think adding custom formats works

Oh boy. Here's my first 🤦🏼 moment on this project.

So I guess that means you can only customise the format of pre-defined formats. I'll just select the most suitable format in each instance then.

2024-10-17 17:21 UTC, bmispelon commented
Here's hoping to many more 🤦🏻 moments, that just means we're doing exciting things 😁 

I didn't know before reviewing your PRs that you could use named formats, so I'm happy to be learning new things.

2024-10-18 20:08 UTC, bmispelon requested changes
Almost there, I think we're done to one final template! 🏁

2024-10-18 20:08 UTC, bmispelon commented on djangoproject/templates/blog/entry_archive_year.html
> +{% block title %}{{ year|date:"YEAR_MONTH_FORMAT" }} | {% translate "Weblog" %}{% endblock %}
I don't think that's the right named format to use here, I'd just keep using the year:
```suggestion
{% block title %}{{ year|date:"Y" }} | {% translate "Weblog" %}{% endblock %}
```

(also in the other two instances later in the file)

2024-11-17 20:37 UTC, bmispelon approved these changes
Thanks! 🎸

2024-11-17 20:38 UTC, merged