feat: Translation preparation for the project templates
django/djangoproject.com pull request #1672
Opened 2024-10-16 11:08 UTC by marksweb

This adds translations tags to the project level templates (those not corresponding to an app name) as suggested in [#1648](https://github.com/django/djangoproject.com/issues/1648)

2024-10-23 19:08 UTC, bmispelon requested changes
Thanks again for this herculean work (and not sisyphean I hope 😁 ).

I spotted a few issues, can you also make sure the branch is rebased on the latest `main`, to make sure we've picked up all latest changes?

Thanks! ✨

2024-10-23 23:56 UTC, marksweb commented on djangoproject/templates/registration/password_reset_email.html
> +{% autoescape off %}
No, I pondered that, but didn't stop long enough to work it out.

2024-10-23 23:59 UTC, marksweb commented on djangoproject/templates/donate_thanks.html
> +  <h3><a href="https://www.djangoproject.com/foundation/donate/"><img src="https://www.djangoproject.com/s/img/badges/djangodonated126x54.gif" border="0" alt="{% translate "I donated to Django" %}" w
I think so. Alt text is to help people understand an image so that's what I was going for here.

2024-10-24 00:02 UTC, marksweb commented on djangoproject/templates/diversity/changes.html
>      <dt>Jun 16, 2015</dt>
Good catch. And yes I understand your point that there might be things we miss through this phase, but if we do it's easy to pick things up as they're noticed.

There's also a lot of dates like this in the releases app. I wondered the same thing but don't have a solution to localising these yet beyond translating the month. Months are already translated and I think people can make sense of the year and day if given.

2024-10-24 00:08 UTC, marksweb commented on djangoproject/templates/base_community.html
> +  {% spaceless %}
Think I'll remove that. Don't think I intended for it to get committed.

2024-10-27 12:42 UTC, bmispelon requested changes

2024-10-27 12:42 UTC, bmispelon commented on djangoproject/templates/diversity/changes.html
> +    <dt>{% translate "June" %} 16, 2015</dt>
This won't work either unfortunately (in french for example, the day comes before the month name).

I haven't tested it, but I think a custom tag like this should work:
```
from datetime import date

from django import template
from django.template.defaultfilters import date as datefilter

register = template.Library()


@register.simple_tag
def isodate(datestr, dateformat="DATE_FORMAT"):
    """
    Convert the given string to a date object (ISO) then format it using
    the given format (using Django's |date template filter)
    """
    d = date.fromisoformat(datestr)
    return datefilter(d, dateformat)
```
Then you can use it like so:
```suggestion
    <dt>{% isodate "2015-06-16" %}</dt>
```

2024-10-27 12:44 UTC, bmispelon commented on djangoproject/templates/diversity/changes.html
>      <dt>Jun 16, 2015</dt>
I've made a suggestion in another thread for a custom tag solution that I think could work. Let me know what you think there.

2024-10-28 00:12 UTC, marksweb commented on djangoproject/templates/diversity/changes.html
> +    <dt>{% translate "June" %} 16, 2015</dt>
Ooo clever. I'll try that out. I was going for the "people will make sense of this" approach rather than thinking of a solution!

I'll try this out.

2024-11-01 21:47 UTC, bmispelon requested changes
Some tests for the new template tag would be nice

2024-11-01 21:47 UTC, bmispelon commented on releases/templatetags/date_format.py
> +def isodate(datestr, dateformat="DATE_FORMAT"):
Needs some tests:
```
    def test_isodate(self):
        self.assertEqual(isodate("2005-07-21"), "July 21, 2005")

    def test_isodate_explicit_format(self):
        self.assertEqual(isodate("2005-07-21", "Ymd"), "20050721")

    @override_settings(LANGUAGE_CODE="nn")
    def test_isodate_translated(self):
        self.assertEqual(isodate("2005-07-21"), "21. juli 2005")
```
(in `releases/tests.py::TestTemplateTags` for example)

2024-11-02 00:42 UTC, marksweb commented on releases/templatetags/date_format.py
> +def isodate(datestr, dateformat="DATE_FORMAT"):
Yes, fair point 👍🏼  Thanks for writing some more of this 😆

2024-11-02 11:12 UTC, bmispelon commented on releases/tests.py
> +        self.assertEqual(isodate("2005-07-21"), "juli 21, 2005")
Oh this is interesting. On my machine this test fails:
```
======================================================================
FAIL: test_isodate_translated (releases.tests.TestTemplateTags.test_isodate_translated)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tisba/Programming/djangoproject.com/venv/lib/python3.12/site-packages/django/test/utils.py", line 443, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tisba/Programming/djangoproject.com/releases/tests.py", line 78, in test_isodate_translated
    self.assertEqual(isodate("2005-07-21"), "juli 21, 2005")
AssertionError: '21. juli 2005' != 'juli 21, 2005'
- 21. juli 2005
+ juli 21, 2005


----------------------------------------------------------------------
```

As far as I know, the correct version should be "21. juli 2005" (see the source code for the nn format in Django: https://github.com/django/django/blob/main/django/conf/locale/nn/formats.py#L5). That means something funny is going on with the way the CI is setting up the locale for the tests.

Does that test work as-is on your own machine?

2024-11-02 12:31 UTC, marksweb commented on releases/tests.py
> +        self.assertEqual(isodate("2005-07-21"), "juli 21, 2005")
Yeah the example you provided didn't work for me so I put in what the test compared to.

Why is there a difference though?! 😱😬

2024-11-02 12:36 UTC, marksweb commented on releases/tests.py
> +        self.assertEqual(isodate("2005-07-21"), "juli 21, 2005")
The only thing I could think of was that the django upgrade had merged and I'd not ran this against the latest, but just rebased against `main` and cleaned out my tox dir and I'm still seeing tests pass. :needmytinfoilhatemojihere:

2024-11-02 15:28 UTC, bmispelon commented on releases/tests.py
> +        self.assertEqual(isodate("2005-07-21"), "juli 21, 2005")
There must be a difference in the system configuration between tox/you on one side, and me on the other (I suspect I have some `nn`-related locale stuff installed on my system which might play a role here). I'm going to dig a little bit more ⛏️

2024-11-03 12:43 UTC, marksweb commented on releases/tests.py
> +        self.assertEqual(isodate("2005-07-21"), "juli 21, 2005")
Yeah I certainly dont have anything setup for languages on my machine. It's very much vanilla macOS for an English speaking user. 

(Our education system did a terrible job of trying to teach me French and Spanish for a few years 😂)

2024-11-17 02:05 UTC, marksweb commented
@bmispelon Thanks - I've rebased and corrected an "effect" vs "affect" issue.

2024-11-17 17:14 UTC, bmispelon approved these changes
Excellent work 👍🏻

2024-11-17 17:17 UTC, merged