feat: Translation preparation for fundraising app
django/djangoproject.com pull request #1687
Opened 2024-10-23 19:04 UTC by marksweb

This adds translations tags to the fundraising app as suggested in [#1648](https://github.com/django/djangoproject.com/issues/1648)

2024-10-27 13:45 UTC, bmispelon requested changes
The plaintext files need to be handled a bit differently since spaces and newlines there are significant (unlike in HTML).

Localization is hard work, isn't it? 😁

2024-10-27 13:45 UTC, bmispelon commented on djangoproject/templates/fundraising/index.html
> +        <a href="https://django.threadless.com/" target="_blank">Official merchandise store</a> -
Out of scope for this PR, but I wonder if this is a problem with a known solution:

with the current translation infrastructure, translators have the power to do some significant  (and potentially malicious) modifications to the HTML like changing the `href` or even injecting a `<script>` tag.
Are there tools that can help with that, or is that something that needs to be verified by hand for each language/string?

2024-10-27 13:45 UTC, bmispelon commented on djangoproject/templates/fundraising/manage-donations.html
> +      <input type="submit" class="cta" value="{% translate "Save &rarr;" %}">
We should have a comment for translators or maybe a context marker to indicate what is being saved since that might influence the form of the verb used.

2024-10-27 13:45 UTC, bmispelon commented on fundraising/forms.py
> +        label=_("I am donating as an"),
This probably won't work in every language (even in English, it's only correct now because both choices start with a vowel). But I don't have a suggestion for how to fix it, so it's probably good enough for now

2024-10-27 13:45 UTC, bmispelon commented on fundraising/forms.py
> +        ("custom", _("Other amount")),
The other choice need to be marked as translatable as well

2024-10-27 13:45 UTC, bmispelon commented on djangoproject/templates/fundraising/email/thank-you.html
> +{% load i18n %}
This file has an `.html` extension but is clearly plaintext, no? If so then the same remarks about `trimmed` and preserving newlines apply.

2024-10-27 22:29 UTC, marksweb commented on djangoproject/templates/fundraising/email/payment_failed.txt
> +{% blocktranslate trimmed %}
Yes good point - that's my `blocktranslate` habbits showing because trimming the HTML makes for nicer `.po` files.

2024-10-27 23:59 UTC, marksweb commented on fundraising/forms.py
> +        label=_("I am donating as an"),
Yeah I think it's one to address when someone has a solution

2024-10-28 00:07 UTC, marksweb commented
@bmispelon Ok, I _think_ I've addressed all the issues here - thanks for another review!

2024-10-28 13:52 UTC, bmispelon requested changes
There's still an issue with plaintext templates: the `{ %blocktranslate %}` are inserting extra new lines.

Here's the code I used to test this:
```
from django.template import loader
print(loader.get_template("fundraising/email/payment_failed.txt").render({"donation":{"donor": {"pk": 1234, "name_with_fallback": "TEST"}}}))
```

If you run this code on `main` vs. `marksweb:feat/i18n-fundraising/1648` you'll see extra blank lines between paragraphs. Ideally, the output should be identical.

2024-10-29 01:12 UTC, marksweb commented
@bmispelon Ah yes, apologies - didn't realise that `blocktranslate` created space like this. 🤦🏼 

I've corrected the 3 email templates - though we are adding a blank line at the end of files so there is that still.




```
>>> from django.template import loader
>>> print(loader.get_template("fundraising/email/payment_failed.txt").render({"donation":{"donor": {"pk": 1234, "name_with_fallback": "TEST"}}}))
Hi TEST,

This is to let you know that payment for your recurring donation to the Django Software Foundation has failed.
This might be because your payment card has expired.

Please go to http://www.djangoproject.localhost:8000/fundraising/manage-donations/1234/ to add a new card. We won't be able to take any payments in the mean time.

Thanks very much for your support.

Regards,
Django Software Foundation

>>> print(loader.get_template("fundraising/email/subscription_cancelled.txt").render({"donation":{"donor": {"pk": 1234, "name_with_fallback": "TEST"}}}))
Hi TEST,

This is to let you know that your recurring payment to the Django Software
Foundation has been cancelled. No further payments will be made.

If you didn't intend to do this, please go back to the fundraising page and
recreate your payment subscription:
http://www.djangoproject.localhost:8000/fundraising/
Thanks very much for your support.

Regards,
Django Software Foundation

>>> print(loader.get_template("fundraising/email/thank-you.html").render({"donation":{"donor": {"pk": 1234,}}}))
Hello!

Thank you for making a donation to the Django Software Foundation.

Your support is invaluable to continue the rapid development of Django and helps the Django Fellowship program in particular.

If you want to change information about your donation, you can do so by accessing the link below:

http://www.djangoproject.localhost:8000/fundraising/manage-donations/1234/

Best regards,
Django Software Foundation
```

2024-11-01 20:59 UTC, bmispelon approved these changes

2024-11-01 20:59 UTC, bmispelon commented on djangoproject/templates/fundraising/email/payment_failed.txt
> +{% load i18n %}{% spaceless %}{% url 'fundraising:manage-donations' donation.donor.pk as manage_url %}
Clever use of `spaceless` 👍🏻

2024-11-01 21:00 UTC, merged