Updated Sphinx and related dependencies.
django/djangoproject.com pull request #1694
Opened 2024-10-24 16:33 UTC by pauloxnet

As noted in #1634, the latest version of Sphinx has been used in the Django repository for a long time without any problems.

I tested locally the documentation generation without any problems: `python -m manage update_docs --update-index --force`

Of course, this PR is blocked by the Python 3.8 removal issue #1644

2024-10-24 20:15 UTC, marksweb requested changes
I think while we're supporting python 3.8 docutils needs pinning to [0.20.1](https://pypi.org/project/docutils/0.20.1/) because after that they drop 3.8 support.

2024-10-24 20:15 UTC, marksweb commented on requirements/common.txt
> +docutils==0.21.2
with the 0.21 release, python 3.8 was dropped which is what will be causing the test issues for 3.8.

2024-10-24 20:25 UTC, marksweb commented on requirements/common.txt
> +docutils==0.21.2
With the on hold label, I guess this is waiting on #1644 

There is also #1575 which could be merged in the meantime.

2024-10-24 20:40 UTC, pauloxnet commented on requirements/common.txt
> +docutils==0.21.2
> With the on hold label, I guess this is waiting on #1644

Exactly, I also wrote it in the description.

BTW I'm running the doc update and index locally with the latest Sphinx version and Python 3.12 without any problems.

2024-10-31 00:20 UTC, pauloxnet commented
I rebased this PR and flagged ready for review because issue #1644 is solved.

2024-11-01 01:22 UTC, marksweb approved these changes
LGTM 🎉

2024-11-01 20:48 UTC, bmispelon commented
Thanks everyone ✨

2024-11-01 20:48 UTC, merged