Add a link to Individual membership in the site footer
django/djangoproject.com pull request #1726
Opened 2024-11-07 18:42 UTC by jonafato

Finding information about Individual membership can be difficult if one does not already know where to look. The current path to this page from the homepage is via the footer at Learn More -> Django Software Foundation -> Individual Members. This change is in the same spirit as pull request #1461, which added a link to the Corporate membership page in the footer for similar discoverability reasons.

2024-11-07 21:35 UTC, bmispelon requested changes
I think this makes sense, especially in light of #1461 as you pointed out.

Just have a small suggestion, looks good otherwise.

Thanks for taking the time for this! ✨

2024-11-07 21:35 UTC, bmispelon commented on djangoproject/templates/includes/footer.html
> +            <li><a href="/foundation/individual-members/">Individual membership</a></li>
I'd use the URL name here instead of hardcoding the link:
```suggestion
            <li><a href="{% url 'individual-members' %}">Individual membership</a></li>
```

2024-11-07 21:37 UTC, jonafato commented
@bmispelon Thanks! Suggestion committed.

2024-11-07 21:47 UTC, bmispelon commented
Oops sorry, that url tag should have been `{% url 'members:individual-members' %}` (I'd only skimmed the `members/urls.py` file and missed the `app_name`).

Glad the tests caught that 😅

2024-11-07 21:51 UTC, jonafato commented
Updated and squashed into a single commit. Hopefully third time's the charm.

2024-11-07 21:54 UTC, bmispelon approved these changes
Tested things locally and it works (tested both on the `www` and `docs` subdomains) 👍🏻

2024-11-07 21:58 UTC, bmispelon commented
Would you mind filing another PR for the same change on `django/code.djangoproject.com`? https://github.com/django/code.djangoproject.com/blob/main/trac-env/templates/site_footer.html#L24

(You'll have to hardcode the full URL there, as `{% url ... %}` won't work)

Thanks! 🚀

2024-11-07 22:04 UTC, jonafato commented
No problem, https://github.com/django/code.djangoproject.com/pull/227

2024-11-08 06:54 UTC, merged

2024-11-08 07:02 UTC, bmispelon commented
Both changes are now live, thanks again ✨