Added links for user-profile stats.
django/djangoproject.com pull request #1737
Opened 2024-11-15 10:31 UTC by sarahboyce

2024-11-15 12:40 UTC, sarahboyce commented on tracdb/testutils.py
> +        return
This is based off the following: https://github.com/django/django/blob/91c879eda595c12477bbfa6f51115e88b75ddf88/django/db/migrations/recorder.py#L63-L66

2024-11-15 20:01 UTC, bmispelon requested changes
I like this change, it's nice to see the profile page getting some love after all this time 💚 

As I mentionned in one comment, can you try to rebase on to the latest main and see if that fixes the errors you experienced that lead to the fix in `testutils`?

Thanks!

2024-11-16 08:00 UTC, sarahboyce commented on tracdb/stats.py
> +    link = get_trac_link(f"owner=~{username}&resolution=fixed")
Ah nice!

2024-11-16 08:06 UTC, sarahboyce commented on accounts/tests.py
> +    def test_user_profile(self):
I kept the "tickets fixed" and "tickets opened" counts in the same test as it is nice to have multiple tickets impacting different counts, but split the rest :+1:

2024-11-16 08:08 UTC, sarahboyce commented on tracdb/stats.py
> +    link = get_trac_link(f"owner=~{username}&resolution=fixed")
It appears that Trac adds that when you use the filters but it is not required:
- https://code.djangoproject.com/query?owner=~sarahboyce
- https://code.djangoproject.com/query?owner=sarahboyce
So removed :+1:

2024-11-16 08:12 UTC, sarahboyce commented on djangoproject/templates/accounts/user_profile.html
> +            <h2>{% translate "Statistics on Django core contributions:" %}</h2>
I think you jest :+1: 
But in case I should justify, I'm conscious we should avoid cultural references when dealing with a global audience with a wide range of ages groups

2024-11-16 08:13 UTC, sarahboyce commented
Thank you for the thorough review - I pushed up changes :+1:

2024-11-16 10:09 UTC, bmispelon commented on djangoproject/templates/accounts/user_profile.html
> +            <h2>{% translate "Statistics on Django core contributions:" %}</h2>
I agree with you 🃏 

References can be fine, but I think this one is quite jarring when you don't know it, and definitely doesn't fit the tone of what we're going for.

2024-11-16 11:07 UTC, bmispelon requested changes
Thanks for the quick update!

Most of my comments are nitpicks about the testing style (I find tests with multiple assertions confusing, but that's probably a personal taste).

The one thing that's actually a bug is the behavior change where stats with a zero count were previously hidden from the profile page but are now visible (that's caused by the `StatData` change and the following incorrect `if v == 0` in `views.get_user_stats()`).

Nice work! 🚀

2024-11-16 11:07 UTC, bmispelon commented on accounts/tests.py
> +    def test_stat_tickets_triaged(self):
I'd split this test in 3 o make it clearer what we're testing (test 3 here was missing and refers to the comment in `new_tickets_reviewed()`)
```
test_stat_tickets_triaged():
    # possible values are from trac.ini in code.djangoproject.com
    1 ticket for user1, Unreviewed -> Accepted
    1 ticket for user1, Unreviewed -> Someday/Maybe
    1 ticket for user1, Unreviewed -> Ready for checkin
    1 ticket for user2, Unreviewed -> Accepted
    assert user1 has count 3
    # no assertion for user2 (it's there to make sure only user1 changes
    # are counted)

test_stat_tickets_triaged_unaccepted_not_counted():
    1 ticket Unreviewed -> Accepted
    1 ticket Accepted -> Unreviewed
    assert user1 has count 1

test_stat_tickets_triaged_ticket_accepted_multiple():
    1 ticket with 2 Unreviewed -> Accepted changes
    assert user1 has count 2
```

2024-11-16 11:07 UTC, bmispelon commented on accounts/tests.py
> +        accepts_ticket = {
That's clever to use a dict like this 👍🏻

2024-11-16 11:32 UTC, sarahboyce commented on accounts/tests.py
> +    def test_stat_tickets_triaged(self):
The last test `test_stat_tickets_triaged_ticket_accepted_multiple` is currently not possible because `TicketChange` has been modeled with the ticket as a primary key with the comment `# XXX See note at the top about composite pk`

2024-11-16 11:33 UTC, sarahboyce commented on accounts/tests.py
> +            rev="91c879eda595c12477bbfa6f51115e88b75ddf88",
Sorry I picked a couple of random recent ones :sweat_smile:

2024-11-16 11:35 UTC, sarahboyce commented on accounts/tests.py
> +        accepts_ticket = {
I think some model factory thing would be nice in future

2024-11-16 12:02 UTC, bmispelon commented on accounts/tests.py
> +    def test_stat_tickets_triaged(self):
My bad, I forgot about that 🤦🏻  (the actual table has a 3-column primary key `ticket, time, field` which is ... a choice)

2024-11-16 12:04 UTC, bmispelon commented on accounts/tests.py
> +        accepts_ticket = {
> I think some model factory thing would be nice in future

I tell myself this every time I write tests that involves a lot of models, but somehow it always seem like too big an investment for the current PR, and then I never get around to it. Classic sunk cost fallacy I guess ⛵

2024-11-17 20:27 UTC, bmispelon approved these changes
Great work, thanks! 👍🏻

2024-11-17 20:28 UTC, merged