feat: Translation preparation for members app
django/djangoproject.com pull request #1742
Opened 2024-11-18 00:03 UTC by marksweb

This adds translations tags to the members app as suggested in [#1648](https://github.com/django/djangoproject.com/issues/1648)

Lost this branch amongst all the others!

2024-11-18 18:21 UTC, bmispelon requested changes
Nice one 👍🏻 

Found a few missing strings and some that should be changed a bit. I wasn't sure about the `spaceless` trick in the text template but I tried it and it does seem to work, nice find (you should blog about that 😉 )

2024-11-18 18:21 UTC, bmispelon commented on members/admin.py
> +from django.utils.translation import gettext_lazy as _
(not the correct line, but I can't seem to add comments to unmodified lines)

More things need to be marked as translatable here:

- `StatusFilter.title`
- The `alt` text in `CorporateMemberAdmin.renewal_link()`

2024-11-18 18:21 UTC, bmispelon commented on members/forms.py
> +from django.utils.translation import gettext_lazy as _
(again, marking this on the wrong line)

The various strings inside `save()` also need to be marked as translatable. There will also need to be some refactoring to avoid building the sentence piecemeal and instead have full sentences be marked as translatable (I think we did something similar in another pull request but I can't remember which one now).

2024-11-18 18:21 UTC, bmispelon commented on members/views.py
> +                _("No %(verbose_name)s found matching the query")
This type of sentence building doesn't work well in many languages (since the `verbose_name` form might not be correct for the context of this sentence).

I suggest removing the clever `verbose_name` interpolation and hardcoding the model name in a regular translated string (this code seems like it's only used with `model=CorporateMember`)

2024-11-18 21:18 UTC, marksweb commented on members/forms.py
> +from django.utils.translation import gettext_lazy as _
OK I've approached this email from and `if/else` on the renewal flag.

2024-11-19 20:30 UTC, bmispelon approved these changes
Great work (and great blog post too!) 🚀

2024-11-20 03:44 UTC, marksweb commented
> @marksweb I noticed that the last commit on the branch was made with a different commit than usual, was that on purpose?

Very well spotted! No it was not on purpose.

I've been changing my shell setup & things are still in flux. Though looking at my git config I'm not sure what put my personal email on django commits. Anyway - I've added a config entry.

Thank you - expert reviewing!

2024-11-21 12:34 UTC, merged