Only return published blog entries.
django/djangoproject.com pull request #1757
Opened 2024-11-20 23:01 UTC by marksweb

This fixes #1755 to only return published blog entries, even for staff users.

Unpublished entries can still be previewed via the admin.

2024-11-20 23:02 UTC, marksweb commented
On a side note, my test suite is failing me and I'm not sure why.

```
======================================================================
ERROR: blog.tests (unittest.loader._FailedTest.blog.tests)
----------------------------------------------------------------------
ImportError: Failed to import test module: blog.tests
Traceback (most recent call last):
  File "/Users/mark/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/lib/python3.12/unittest/loader.py", line 396, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mark/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/lib/python3.12/unittest/loader.py", line 339, in _get_module_from_name
    __import__(name)
  File "/Users/mark/dev/djangoproject.com/blog/tests.py", line 2, in <module>
    from test.support import captured_stderr
ModuleNotFoundError: No module named 'test'
```

2024-11-20 23:55 UTC, jefftriplett commented on blog/views.py
> +        return Entry.objects.published()
This change is good, but I would move the deleted `get_queryset()` into the `BlogDateDetailView` view so we can still preview the Entry on the website. Otherwise, I don't think we'll be able to proofread the rst and markdown rendering since the admin doesn't have a true preview feature.

2024-11-21 00:03 UTC, pauloxnet commented on blog/views.py
> +        """ """
I would remove or add some text.

2024-11-21 00:42 UTC, marksweb commented on blog/views.py
> +        """ """
🤦🏼‍♂️ I was about to, then decided we all know what it does and it's not that complicated. Can't believe I missed that.

2024-11-21 00:43 UTC, marksweb commented on blog/views.py
> +        return Entry.objects.published()
Ah, fair point - the way I read your issue I assumed that preview was handled separately.

2024-11-21 00:44 UTC, marksweb commented on blog/views.py
> +        return Entry.objects.published()
Nothing's ever as simple as it looks 😆

2024-11-21 07:03 UTC, bmispelon requested changes
Thanks for the quick response on this, nice work 👍🏻 

If you allow me to change/extend the scope of this PR a little bit, I think it's not enough to test for `user.is_staff` but we should also make sure that the user has write permissions on the `BlogEntry` model (since this feature is meant to be used for previewing).

And there should also be some tests added (I'm suprised there weren't already, or that if there were they were still passing after this change):
- anon users can't see unpublished entries at all (list or detail)
- logged in users (non-staff) can't see unpublished entries at all
- staff users without write permission on `BlogEntry` can't see unpublished entries at all
- staff users with write permission on `BlogEntry` can't see unpublished entries in the list, but can view the detail page

2024-11-21 15:00 UTC, jefftriplett commented
@marksweb this is great. Thank you for jumping in on this.

2024-11-21 15:02 UTC, marksweb commented
> And there should also be some tests added (I'm suprised there weren't already

Yes I was surprised & expecting you to suggest this 😄

2025-04-18 08:07 UTC, marksweb commented
> Thanks for the quick response on this, nice work 👍🏻
> 
> If you allow me to change/extend the scope of this PR a little bit, I think it's not enough to test for `user.is_staff` but we should also make sure that the user has write permissions on the `BlogEntry` model (since this feature is meant to be used for previewing).
> 
> And there should also be some tests added (I'm suprised there weren't already, or that if there were they were still passing after this change):
> 
>     * anon users can't see unpublished entries at all (list or detail)
> 
>     * logged in users (non-staff) can't see unpublished entries at all
> 
>     * staff users without write permission on `BlogEntry` can't see unpublished entries at all
> 
>     * staff users with write permission on `BlogEntry` can't see unpublished entries in the list, but can view the detail page

Ok, it took longer than I expected, but I've added tests and enforced permissions.

2025-05-20 13:26 UTC, adamzap requested changes

2025-05-20 13:26 UTC, adamzap commented on blog/tests.py
> +
Could we drop this blank line to stay consistent with the rest of the file?

2025-05-20 13:26 UTC, adamzap commented on blog/tests.py
> +    def test_staff_with_write_permission_can_see_unpublished_detail_view(self):
Do you think it would be a bit better if we changed "write" to "change" in the test name and the docstring? Maybe elsewhere in this PR too? That way it would match the name of the permission. I don't feel strongly about this.

2025-05-20 13:26 UTC, adamzap commented on blog/tests.py
> +        staff users with write permission on BlogEntry can't see unpublished entries
Could we capitalize the first word in these comment to stay consistent with the rest of the file?

2025-05-20 13:26 UTC, adamzap commented on blog/tests.py
> +        from django.contrib.contenttypes.models import ContentType
Could we import these at the top of the file instead, or is there a side affect necessitating this?

2025-05-20 13:26 UTC, adamzap commented on blog/tests.py
> +        # Test detail view for unpublished entry - should return 404
I think comments like this are implied by the test name and the assert(s), but we can keep them if you or others find them helpful.

2025-05-21 01:43 UTC, adamzap commented on blog/tests.py
> +        # Test detail view for unpublished entry - should return 404
Ok cool!

2025-05-21 14:25 UTC, pauloxnet reviewed
I added 2 minor suggestions.

2025-05-21 14:25 UTC, pauloxnet commented on blog/views.py
> +            return Entry.objects.published()
```suggestion
            return self.get_queryset()
```
I would reuse `get_queryset` from `BlogViewMixin`.

2025-06-05 19:53 UTC, marksweb commented on blog/views.py
> +            return Entry.objects.published()
Ok, that's fair :+1:

2025-07-14 22:41 UTC, adamzap commented
@marksweb Could you check the CI failure here?

2025-07-15 02:03 UTC, marksweb commented
> @marksweb Could you check the CI failure here?

Done - there was an actual issue I'd not spotted 🤦🏼

2025-07-16 15:38 UTC, adamzap commented
@bmispelon Do you have any concerns here, or can we merge this?

2025-07-30 18:22 UTC, bmispelon approved these changes
Nice work Mark, thanks for this! 👍🏻

2025-08-03 19:05 UTC, merged