Fixed the atomic transaction issue
django/djangoproject.com pull request #1768
Opened 2024-11-23 18:21 UTC by arpan8925

1. Added **@transaction.atomic decorator** to the **checkout_session_completed** method

2. All database operations are now wrapped in a transaction:

        - Creating/getting the DjangoHero
        - Creating the Donation
        - Creating the Payment (for one-time donations)

2024-11-23 18:27 UTC, arpan8925 commented
Solved issue of #1764

2024-11-24 11:41 UTC, bmispelon requested changes
Hi and thanks for working on this! 🎸 

Decorating `checkout_sesion_completed()` like this shoudl work I think, but I'm not sure it's the best place to add the `atomic` block. If instead we had `with transaction.atomic()` before calling `handler()` inside `WebhookHandler.handle()`, then all web hooks would be fixed, not just the one.

There also need to be tests added, to make sure the behavior continues to work even as we refactor the code in the future.

Let me know what you think!

2024-11-24 11:41 UTC, bmispelon commented on fundraising/views.py
> +        all changes will be rolled back to maintain data consistency.
This addition is not needed

2024-11-24 15:44 UTC, arpan8925 commented
@bmispelon Check if it fixes the issue, I made a separate file for the webhook test, review please

2024-11-25 16:08 UTC, arpan8925 commented
It Seems , test working now !

The test is failing because the webhook handler isn't properly handling the InvalidRequestError from Stripe.

However, Everything fixed.. Please Check & Review

2024-11-25 16:44 UTC, arpan8925 commented
![image](https://github.com/user-attachments/assets/0a45b79c-95b0-4631-8e33-d620ae84f619)

2024-11-27 06:10 UTC, arpan8925 commented
@bmispelon  Can you review ?

2024-11-30 07:24 UTC, arpan8925 commented
@bmispelon

2024-11-30 15:49 UTC, marksweb commented
@arpan8925 I'm sure you'll get another review on here when someones free to do so. We're all volunteers here doing this in our free time.

2024-12-03 13:19 UTC, bmispelon commented
Hi,

There are several issues with your PR:
* This version is very different and much more complicated than the one you submitted initially, and it contains unexplained code changes
* Instead of adding a new test method to the `TestWebhooks` you created a whole new file with some of the old tests copy/pasted.
* There are now conflicts with other changes that have been merged since this pull request was opened (this is related to the first point)

Could you revert the changes and go back to the version you had at the beginning with only a `with atomic()` block? Then I will make some proposals for how to add tests for that.

Thanks! 🎸

2025-05-14 18:50 UTC, closed without merging