Fix #1727 -- Retire django-developers and django-users mailing list
django/djangoproject.com pull request #1805
Opened 2024-12-08 01:24 UTC by ontowhee

Fix for #1727 

I've removed the references to the mailing lists. I hope it looks good!

### Footer

Before
![footer-mailing-list-before](https://github.com/user-attachments/assets/d5e89286-ecd6-4445-8185-350d9fcf3a06)

After
![footer-mailing-list-after](https://github.com/user-attachments/assets/500f4220-f726-4b39-a5da-a49ddf731ba0)

### Community

Before
![community-mailing-list-before](https://github.com/user-attachments/assets/37fb47c6-4fd1-4fe5-afe3-fa0f32437b7c)

After
![community-mailing-list-after](https://github.com/user-attachments/assets/82cb2d3b-cc6c-4f1b-a17b-e67a3f9c2260)

### Download page

Before
![download-mailing-list-before](https://github.com/user-attachments/assets/ec5c9763-97b1-4385-86dc-b893359b5369)

After
![download-mailing-list-after](https://github.com/user-attachments/assets/2ab40ca7-bdda-4701-91cf-7ae0353d4d30)

### Homepage

Before
![homepage-mailing-list-before](https://github.com/user-attachments/assets/95347813-4e48-44be-accd-c27c8ab8313e)

After
![homepage-mailing-list-after](https://github.com/user-attachments/assets/4e48635f-7eb3-407e-9f11-a0917385dc5b)

2024-12-08 10:10 UTC, bmispelon requested changes
This is a great start, thanks for working on this 🙇🏻 

Using `git grep mailing.list` I found more places that should be fixed:
- [x] `djangoproject/templates/contact/foundation.html`
- [x] `docs/templates/docs/doc.html`

There's also things inside `djangoproject/templates/conduct/` that should be updated, but I don't know if that requires approval from the CoC work group. I'll ask around, we can do it in a separate PR later.

2024-12-08 10:10 UTC, bmispelon commented on djangoproject/templates/aggregator/index.html
> -  {% include "includes/mailing_lists.html" %}
This included template is not used anymore now and can be deleted

2024-12-08 10:10 UTC, bmispelon commented on djangoproject/templates/releases/download.html
> +  <p>And be sure to sign up to the <a href="https://forum.djangoproject.com">Django Forum</a>, where other Django users and the Django developers themselves all hang out to help each other.</p>
Nice rewrite 👍🏻

2024-12-08 14:38 UTC, ontowhee commented on djangoproject/templates/aggregator/index.html
> -  {% include "includes/mailing_lists.html" %}
Thanks for pointing this out! It is now deleted!

2024-12-08 14:48 UTC, ontowhee commented
I've updated `djangoproject/templates/contact/foundation.html` and `docs/templates/docs/doc.html`. Thanks for mentioning these! I've added their screenshots to the PR description.

2024-12-08 17:08 UTC, bmispelon approved these changes
This is looking great, nice work 👍🏻 

Thanks for taking the time to take screenshots too, it made reviewing even easier 🙇🏻

2024-12-08 17:10 UTC, merged

2024-12-11 10:59 UTC, thibaudcolas commented
Thank you! 😌 Now we have to figure out what to do with all that space on the homepage!